controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    speed_scaling_state_controller:
      type: ur_controllers/SpeedScalingStateController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    force_torque_state_controller:
      type: ur_controllers/ForceTorqueStateController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

speed_scaling_state_controller:
  ros__parameters:
    state_publish_rate: 100.0

forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position

force_torque_state_controller:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - fx
      - fy
      - fz
      - tx
      - ty
      - tz
    frame_id: tool0
    topic_name: ft_data
