name: Build Source
on:
  push:
    branches:
      - master
      - develop
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '43 1 * * *'

jobs:
  source:
    name: source build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.0.26
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name:
            Universal_Robots_ROS2_Driver
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Universal_Robots_ROS2_Driver.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
