name: Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # Old config - moved in ci-format.yml
        # linter: [copyright, cppcheck, cpplint, flake8, pep257, uncrustify, xmllint]
        linter: [copyright]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.1
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name:
          Universal_Robots_ROS2_Driver
