name: ROS2 Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.1
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name:
          ros2_control_demo_hardware
          ros2_control_demo_robot
          ros2_control_demos
