name: Foxy Binary Build
on:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '58 11 * * *'

jobs:
  foxy_binary:
    name: foxy binary build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    env:
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: foxy
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
