name: Humble Execution Test
on:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 22 * * *'
  workflow_dispatch:

jobs:
  binary_test:
    name: ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }}) binary execution test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        ROS_DISTRO: [humble]
        ROS_REPO: [main, testing]
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.${{ matrix.ROS_DISTRO }}.repos
      DOCKER_RUN_OPTS: --network ursim_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: humble
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
