name: Jazzy Binary Build Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  jazzy_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: jazzy
      ros_repo: main
      ref_for_scheduled_build: main
