name: Kilted Binary Build Main
on:
  workflow_dispatch:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  kilted_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: main
      ref_for_scheduled_build: kilted
