name: Kilted Binary Build Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - kilted
  push:
    branches:
      - kilted
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  kilted_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: testing
