name: Rolling Source Build
on:
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '43 1 * * *'

jobs:
  rolling_source:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    container:
      image: ubuntu:jammy
    env:
      ROS_DISTRO: rolling
      ros_version: 2
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          # build all packages listed in the meta package
          package-name:
            ur_bringup
            ur_controllers
            ur_dashboard_msgs
            ur_moveit_config
            ur_robot_driver
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Universal_Robots_ROS2_Driver.${{ env.ROS_DISTRO }}.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          skip-tests: true
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
