name: Rolling Semi Binary Build Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  rolling_semi_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: testing
      upstream_workspace: Universal_Robots_ROS2_Driver.rolling.repos
      ref_for_scheduled_build: main
