name: Rolling Binary Build Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  rolling_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: main
      ref_for_scheduled_build: main
      rosdep_skip_keys: >-
        moveit_configs_utils
        moveit_kinematics
        moveit_planners
        moveit_planners_chomp
        moveit_ros_move_group
        moveit_ros_visualization
        moveit_servo
        moveit_simple_controller_manager
